version: "3.8"

services:
    kafka2:
      container_name: kafka2
      hostname: kafka2
      image: hiage/kafka:3.3.1
      restart: always
      build: 
        context: .
      environment:
          - KAFKA_HEAP_OPTS=-Xmx1025m -Xms1025m
      network_mode: host
      extra_hosts:
          - "kafka1: 192.168.144.47"
          - "kafka2: 192.168.144.51"
          - "kafka3: 192.168.144.49"
      volumes:
          - ./timezone:/etc/timezone
          - ./server.properties:/kafka/config/server.properties
          - /data/kafka:/data/kafka/
      ulimits:
        memlock:
          soft: -1
          hard: -1
      healthcheck:
          test: nc -z 127.0.0.1 9092 || exit -1
          interval: 60s
          retries: 5
          start_period: 20s
          timeout: 10s
